---
include:
  - board: nice_nano//zmk
    shield: lily58_left
    # snippet: zmk-usb-logging
    artifact-name: lily58_left
  - board: nice_nano//zmk
    shield: lily58_right
    # snippet: zmk-usb-logging
    artifact-name: lily58_right
  # reset
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset
  # # sweep (cradio)
  - board: nice_nano//zmk
    shield: cradio_left
    artifact-name: sweep_left
  - board: nice_nano//zmk
    shield: cradio_right
    artifact-name: sweep_right
  # dolphin1 (自制 Sweep PCB)
  - board: nice_nano//zmk
    shield: dolphin1_left
    snippet: studio-rpc-usb-uart
    # snippet: zmk-usb-logging
    artifact-name: dolphin1_left
  - board: nice_nano//zmk
    shield: dolphin1_right
    # snippet: zmk-usb-logging
    artifact-name: dolphin1_right
  # # silakka54
  # - board: nice_nano//zmk
  #   shield: lily58_left
  #   snippet: zmk-usb-logging
  #   cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config_silakka54"
  #   artifact-name: silakka54_left
  # - board: nice_nano//zmk
  #   shield: lily58_right
  #   snippet: zmk-usb-logging
  #   cmake-args: -DZMK_CONFIG="${GITHUB_WORKSPACE}/config_silakka54"
  #   artifact-name: silakka54_right
  # bgkeeb
  - board: nice_nano//zmk
    shield: bgkeeb_left
    artifact-name: bgkeeb_left
  - board: nice_nano//zmk
    shield: bgkeeb_right
    artifact-name: bgkeeb_right
