# ==========================================
# Cradio 左手（Dongle 模式 - 从机 Peripheral）专属配置
# ==========================================

# 强制左手降级为从机 (Peripheral)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# 降级为从机后开启深度休眠（从机端休眠能极大省电）
CONFIG_ZMK_SLEEP=y
# 15分钟休眠
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 降级为从机后，不需要也无法启动 ZMK Studio
CONFIG_ZMK_STUDIO=n
