# Ferris Sweep (cradio) 配置
# 蓝牙增强
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 电量上报
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# 深度睡眠 15 分钟
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
