# Display (Nice!View / Sharp Memory LCD)
# CONFIG_ZMK_DISPLAY=y

# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="Silakka54"

# --- 蓝牙稳定性优化 ---
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# 降低发射功率，解决Windows部分设备近距离丢包/连接重置问题
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_TX_PWR_0=y
# Connectivity stability fixes
CONFIG_BT_CTLR_PHY_2M=n

# --- Windows 11 专项修复 ---
# 绕过 Windows 11 烦人的 GATT 电量通知断联 Bug
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# 修复 Win11 断流 + 开启配对码 + 自动覆盖死链接
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
# --- 开启安全配对码 (核心修改) ---
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Battery reporting
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# 开启深度休眠开关 (必须加这一行，Timeout 才会生效)
CONFIG_ZMK_SLEEP=y
# Deep sleep (15 min idle)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Mouse emulation (Layer 5: Mouse)
CONFIG_ZMK_POINTING=y

# Combos (JK=Esc, FJ=CapsWord, DF=Ctrl+Shift)
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=5
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=4
